config/routes.rb
Rails.application.routes.draw do

  get 'link/create'

  root to: 'links#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create]
  resources :links, only: [:create, :edit, :update]
  get '/links/:id', to: 'links#create'
  put '/links/:id/toggle', to: 'links#toggle_read', as: 'toggle_read'

  namespace 'api' do
    namespace 'v1' do
      resources :links, only: [:update]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :url, presence: true, url: true
  validates :read, default: false
  before_create :scrape_html_summary

  def scrape_html_summary
    scraper = WebScraper.new(url)
    self.summary_h1 = scraper.page_h1
    self.summary_title = scraper.page_title
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :links
  validates :email, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < ApplicationController
  protect_from_forgery with: :null_session
  respond_to :json

  def update
    link = Link.find(params[:id])
    if link.update(link_params) && link.valid?
      render json: link
    else
      render status: 500
    end
  end

  private

  def link_params
    params.require(:link).permit(:id, :title, :url, :read)
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    if current_user
      @user = current_user
      @links = current_user.links
    else
      redirect_to login_path
    end
  end

  def create
    link = Link.new(title: params[:link][:title], url: params[:link][:url], user: current_user)
    validate_link(link)
    redirect_to root_path
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    link = Link.find(params[:id])
    if link.update(link_params) && link.valid?
      flash[:notice] = "'#{link.title}' updated."
    else
      flash[:error] = "'#{link.title}' was not updated."
    end
    redirect_to root_path
  end

  private

  def validate_link(link)
    if link.valid?
      link.save
      flash[:success] = "link added!"
    else
      flash[:error] = link.errors.full_messages.join(', ')
    end
  end

  def link_params
    params.require(:link).permit(:id, :title, :url, :read)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid username or password."
      render :new
    end
  end

  def destroy
    session.clear
    flash[:notice] = "Logged out. Come back soon!"
    redirect_to root_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:error] = @user.errors.full_messages.join(', ')
      redirect_to new_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>URLockbox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <%= message %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/links/edit.html.erb
<h1>Edit Link</h1>
  <%= form_for(@link) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :url%>
    <%= f.text_field :url %>
    <%= f.submit "Submit Edits" %>
  <% end %>

app/views/links/index.html.erb
<h3><%= "Logged in as #{current_user.email}" %> <%= link_to "Sign Out", logout_path, method: :delete %></h6>
<%= form_for(:link, url: links_path) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :url%>
  <%= f.text_field :url %>
  <%= f.submit "Add Link" %>
<% end %>
<br>
<input type="text" class="form-control" placeholder="Search Links" id="search-links">
<button id="unread-filter">See All Read Links</button>
<button id="read-filter">See All Unread Links</button>
<button id="show-all">See All Links</button>
<button id="alpha">Sort Alphabetically</button>
<br>
<br>
<table id='link-table'>
  <tr>
    <th>Title</th>
    <th>URL</th>
    <th>Summary</th>
    <th>Read?</th>
    <th>Edit</th>
  </tr>
  <% @links.each do |link| %>
    <tr data-id="<%= link.id %>" class="link link-read-<%= link.read %>">
      <td class="editable-title" contenteditable='true'><%= link.title %></td>
      <td class="editable-url" contenteditable='true'><%= link_to link.url, link.url %></td>
      <% if link.summary_h1 && link.summary_title %>
        <td class="summary"><%= link.summary_h1 %>, <%= link.summary_title %></td>
      <% else %>
        <td><p>No Summary Available</p></td>
      <% end %>
      <% if link.read %>
      <td><%= button_to "Mark as Unread", toggle_read_path(link), method: :put, class: 'read-btn' %></td>
        <% else %>
          <td><%= button_to "Mark as Read", toggle_read_path(link), method: :put, class: 'read-btn' %></td>
      <% end %>
        <td><%= button_to "Edit Link", edit_link_path(link), method: :get, class: 'edit-btn' %>
    </tr>
  <% end %>
</table>